# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

stages:
  - stage: artifact_building
    jobs:
    - job: Build
      displayName: Build Maven Project
      steps:
      - task: Maven@3
        displayName: 'Maven Package'
        inputs:
          mavenPomFile: 'pom.xml'
      - task: CopyFiles@2
        displayName: 'Copy Files to artifact staging directory'
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: '**/target/*.?(war|jar)'
          TargetFolder: $(Build.ArtifactStagingDirectory)
      - upload: $(Build.ArtifactStagingDirectory)
        artifact: drop
  
  - stage: deployment_first
    dependsOn: artifact_building
    jobs:
      - deployment: VMDeploy
        displayName: web
        pool:
          vmImage: 'Ubuntu-latest'
        environment:
          name: NewLinux
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - script: echo my first deployment

  - stage: deployment_second
    dependsOn: deployment_first
    jobs:
      - deployment: VMDeploy
        displayName: web
        environment:
          name: NewLinux
          resourceType: VirtualMachine
        strategy:
          rolling:
            maxParallel: 5  #for percentages, mention as x%
            preDeploy:
              steps:
              - download: current
                artifact: drop
              - script: echo initialize, cleanup, backup, install certs
            deploy:
              steps:
              - task: Bash@3
                inputs:
                  targetType: 'inline'
                  script: |
                    echo "Starting deployment script run"
                    cd '$(Pipeline.Workspace)/drop/**/target/'
                    sudo java -jar './*.jar'
            routeTraffic:
              steps:
              - script: echo routing traffic
            postRouteTraffic:
              steps:
              - script: echo health check post-route traffic
            on:
              failure:
                steps:
                - script: echo Restore from backup! This is on failure
              success:
                steps:
                - script: echo Notify! This is on success